_target_: diffusion_policy.workspace.train_demo_score_hybrid_workspace.TrainDemoScoreHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_loss={val_loss:.3f}.ckpt
    k: 5
    mode: min
    monitor_key: val_loss
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2023.01.03-19.43.07_train_demo_score_image_transport_image
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_demo_score_image
  - transport_image
  - default
multi_run:
  run_dir: data/outputs/2023.01.03/19.43.07_train_demo_score_image_transport_image
  wandb_name_base: 2023.01.03-19.43.07_train_demo_score_image_transport_image
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_demo_score_image
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 0.1
past_action_visible: false
model: 
  _target_: diffusion_policy.classifier.hybrid_image_state_success_classfier.HybridImageStateSuccessClassifier
  shape_meta:
    action:
      shape:
      - 20
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
  n_obs_steps: 2
  crop_shape:
  - 76
  - 76
  hidden_dims: [32, 32, 32]
  dropout: 0.3
  obs_encoder_group_norm: true
  eval_fixed_crop: true  
shape_meta:
  action:
    shape:
    - 20
  obs:
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
    robot1_eef_pos:
      shape:
      - 3
    robot1_eef_quat:
      shape:
      - 4
    robot1_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot1_gripper_qpos:
      shape:
      - 2
    shouldercamera0_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    shouldercamera1_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.episode_classifier_dataset.EpisodeClassifierDataset
    dataset_path: ???  # Set programatically.
    episode_cache_size: 100
    val_ratio: 0.10
    max_train_episodes: 25
    seed: 42
  demo_dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: data/robomimic/datasets/transport/mh/image_abs.hdf5
    horizon: 16
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 20
      obs:
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
        robot1_eef_pos:
          shape:
          - 3
        robot1_eef_quat:
          shape:
          - 4
        robot1_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot1_gripper_qpos:
          shape:
          - 2
        shouldercamera0_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        shouldercamera1_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
    use_cache: true
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/transport/mh/image_abs.hdf5
  dataset_type: mh
  name: transport_image
  shape_meta:
    action:
      shape:
      - 20
    obs:
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
      robot1_eef_pos:
        shape:
        - 3
      robot1_eef_quat:
        shape:
        - 4
      robot1_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot1_gripper_qpos:
        shape:
        - 2
      shouldercamera0_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      shouldercamera1_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
  task_name: transport
task_name: transport_image
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3000
  resume: true
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: false
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
